slack:
    - team: TEAM1
      api_token: TOKEN1
      response_type: default
    - team: TEAM2
      api_token: TOKEN2
      response_type: default
discord:
    - team: TEAM3
      api_token: TOKEN3
      response_type: default
lib:
    google_custom_search:
        api_key: API_KEY
        search_engine_id: SEARCH_ENGINE_ID
        template:
            default:
                text: "<%= data.title %>: <%= data.link %>"
                image: "<%= data.link %>"

